#!/bin/sh
. /lib/lsb/init-functions

case $1 in
	start)
		echo "Starting Torwall"
		torwalld start 1> /dev/null 2> /dev/null &
		;;
	stop)
		echo "Stopping Torwall"
		killall -q -3 tdaemon
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Please run:\n/etc/init.d/torwalldaemon start|stop|restart"
		exit 1
esac
